[package]
name = "big_rand"
version = "0.1.0"
authors = ["Josh Stone <cuviper@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2.11"
rand = "0.9"
rand_chacha = "0.9"
rand_isaac = "0.4"
rand_xorshift = "0.4"

[dependencies.num-bigint]
features = ["rand"]
path = "../.."
