name: CI
on:
  push:
    branches:
      - staging
      - trying

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [
          1.31.0, # 2018!
          1.32.0, # rand
          1.34.0, # quickcheck, has_try_from
          1.36.0, # alloc
          stable,
          beta,
          nightly
        ]
    steps:
      - name: Rust install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Test
        run: ./ci/test_full.sh

  # try a target with `BigDigit = u32`
  i686:
    name: Test (i686)
    runs-on: ubuntu-latest
    steps:
      - name: System install
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib
      - name: Rust install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-i686-unknown-linux-gnu
          profile: minimal
          override: true
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Test
        run: ./ci/test_full.sh

  # try a target that doesn't have std at all, but does have alloc
  no_std:
    name: No Std
    runs-on: ubuntu-latest
    steps:
      - name: Rust install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: thumbv6m-none-eabi
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target thumbv6m-none-eabi --no-default-features --features "serde rand"

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Rust install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.42.0
          profile: minimal
          override: true
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
