name: master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # 00:00 Sunday

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.63.0, stable]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        if: startsWith(matrix.rust, '1')
        with:
          path: ~/.cargo/registry/index
          key: cargo-${{ matrix.rust }}-git-index
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo build
      - run: ./ci/test_full.sh
